'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={pending:'Не проверено',attention:'Требует внимания',reviewed:'Проверки заполнены',verified:'Проверено вручную',flagged:'Выявлены вопросы',clear:'Совпадений нет',match:'Найдено совпадение',error:'Ошибка провайдера'};
const checks={kyb:['Контрагент и бенефициары','Регистрация, структура владения и полномочия подписанта.'],sanctions:['Санкционный скрининг','Списки, дата проверки, совпадения и решение по ним.'],wallet:['Кошелёк и AML','Сеть, принадлежность, источник и дата AML-отчёта.'],funds:['Источник средств','Экономический смысл и подтверждение происхождения средств.'],legal:['Правовое основание','Применимые нормы, условия расчёта и статус оператора.'],documents:['Комплект документов','Договор, инвойс, поставка и место хранения документов.']};
let deals=[],current=null,page='deals',loadError='',auth=null;
async function api(path,options={}){const headers={'Content-Type':'application/json',...options.headers};if(auth&&options.method&&!['GET','HEAD'].includes(options.method))headers['X-CSRF-Token']=auth.csrfToken;const r=await fetch(path,{...options,headers}),data=await r.json();if(!r.ok){const e=Error(data.error||'Ошибка запроса');e.status=r.status;throw e}return data}
const mayWrite=()=>auth&&['owner','compliance'].includes(auth.user.role),badge=s=>`<span class="badge ${esc(s)}">${esc(labels[s]||s)}</span>`,date=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
function toast(m){$('#toast').textContent=m;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500)}
function identity(){const u=auth.user;$('#org-name').textContent=u.organization;$('#profile-name').textContent=u.name;$('#profile-role').textContent={owner:'Владелец',compliance:'Комплаенс',viewer:'Наблюдатель'}[u.role]||u.role;$('#profile-initials').textContent=u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();$('#logout').hidden=false;$('#users-nav').hidden=u.role!=='owner'}
function render(){
 document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#breadcrumb').textContent={deals:'Сделки ВЭД',guide:'Методология',integrations:'Интеграции',users:'Пользователи'}[page];
	if(page==='users'){renderUsers();return}
 if(page==='guide'){$('#page').innerHTML=`<p class="eyebrow">ПРОЦЕСС И ОСНОВАНИЯ</p><h1>Методология проверки</h1><div class="bottom-grid"><article class="info"><h3>Шесть направлений</h3><ol>${Object.values(checks).map(([t,d])=>`<li><b>${t}.</b> ${d}</li>`).join('')}</ol></article><article class="info"><h3>Правовой контекст</h3><p>МНС сообщает о вступлении с 18.07.2026 в силу постановления № 288/13: расчёты токенами по ВЭД через криптобанки допускаются в установленных им случаях.</p><a href="https://nalog.gov.by/news/35808/" target="_blank" rel="noopener noreferrer">Сообщение МНС ↗</a><p class="legal-note">Статус workflow не является юридическим разрешением платежа.</p></article></div>`;return}
 if(page==='integrations'){$('#page').innerHTML=`<p class="eyebrow">ИСТОЧНИКИ ДАННЫХ</p><h1>Интеграции</h1><p class="muted">Ответы сохраняются с датой и SHA-256. Ошибка не считается успешной проверкой.</p><div class="integration-list"><article class="info integration"><div><h3>Chainalysis Sanctions Screening</h3><p>Прямое санкционное совпадение адреса. Не заменяет полный KYT-анализ происхождения средств.</p></div>${badge(auth.amlConfigured?'verified':'error')}</article>${[['Расширенный AML/KYT','Экспозиция, категории риска и мониторинг транзакций требуют коммерческого API.'],['Санкции и PEP контрагентов','Проверка юридических лиц и бенефициаров требует отдельного источника.'],['Реестры компаний','Статус и структура владения требуют отдельного источника.']].map(([t,d])=>`<article class="info integration"><div><h3>${t}</h3><p>${d}</p></div><span class="badge">Не подключено</span></article>`).join('')}</div>`;return}
 $('#page').innerHTML=`<div class="title-row"><div><p class="eyebrow">КОНТРОЛЬ ВНЕШНЕЭКОНОМИЧЕСКИХ СДЕЛОК</p><h1>Сделки ВЭД</h1><p class="muted">Рабочее пространство ${esc(auth.user.organization)}.</p></div>${mayWrite()?'<button class="primary" id="add-deal">＋ Новая сделка</button>':''}</div>${loadError?`<div class="error-banner">${esc(loadError)} <button class="secondary" id="retry">Повторить</button></div>`:''}<div class="stats">${[['Всего сделок',deals.length,'В организации','▦'],['Ожидают проверки',deals.filter(d=>d.status==='pending').length,'Незавершённые проверки','◷'],['Требуют внимания',deals.filter(d=>d.status==='attention').length,'Зафиксированы вопросы','⚑'],['Проверки заполнены',deals.filter(d=>d.status==='reviewed').length,'Результаты внесены','✓']].map(([t,n,s,i])=>`<article class="stat"><span class="stat-mark">${i}</span><div class="stat-label">${t}</div><strong>${n}</strong><small>${s}</small></article>`).join('')}</div><div class="banner"><span class="symbol">i</span><div><b>Провайдер — источник данных, решение принимает специалист</b><p>Chainalysis проверяет прямое санкционное совпадение. AML/KYT и правовое основание фиксируются отдельно.</p></div></div><section class="panel"><div class="panel-top"><div class="panel-title">Реестр сделок <span class="count">${deals.length}</span></div><div class="filters"><input id="search" type="search" aria-label="Поиск сделки" placeholder="Контрагент или договор"><select id="status-filter" aria-label="Статус сделки"><option value="">Все статусы</option><option value="pending">Не проверено</option><option value="attention">Требует внимания</option><option value="reviewed">Проверки заполнены</option></select></div></div><div id="table"></div></section>`;
 if($('#add-deal'))$('#add-deal').onclick=()=>$('#new-dialog').showModal();if($('#retry'))$('#retry').onclick=load;$('#search').oninput=renderTable;$('#status-filter').onchange=renderTable;renderTable();
}
async function renderUsers(){
	$('#page').innerHTML='<p class="eyebrow">ДОСТУП К ОРГАНИЗАЦИИ</p><h1>Пользователи</h1><p class="muted">Владелец создаёт учётные записи и назначает роли.</p><div class="panel"><div class="empty">Загрузка…</div></div>';
	try{const users=await api('/api/users');$('#page').innerHTML=`<div class="title-row"><div><p class="eyebrow">ДОСТУП К ОРГАНИЗАЦИИ</p><h1>Пользователи</h1><p class="muted">Учётные записи ${esc(auth.user.organization)}.</p></div></div><div class="bottom-grid"><section class="panel"><div class="panel-top"><div class="panel-title">Участники <span class="count">${users.length}</span></div></div><div class="table-wrap"><table><thead><tr><th>ПОЛЬЗОВАТЕЛЬ</th><th>EMAIL</th><th>РОЛЬ</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc({owner:'Владелец',compliance:'Комплаенс',viewer:'Наблюдатель'}[u.role])}</td></tr>`).join('')}</tbody></table></div></section><form id="user-form" class="info"><h3>Новый пользователь</h3><label>Имя<input name="name" required maxlength="200"></label><label>Email<input name="email" type="email" required></label><label>Роль<select name="role"><option value="compliance">Комплаенс</option><option value="viewer">Наблюдатель</option><option value="owner">Владелец</option></select></label><label>Начальный пароль<input name="password" type="password" minlength="12" required autocomplete="new-password"></label><p class="muted">Минимум 12 символов. Передайте пароль пользователю защищённым каналом.</p><p class="error" role="alert"></p><button class="primary">Создать</button></form></div>`;$('#user-form').onsubmit=createUser}catch(e){$('#page').innerHTML=`<div class="error-banner">${esc(e.message)}</div>`}
}
async function createUser(e){e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('/api/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});toast('Пользователь создан');await renderUsers()}catch(err){f.querySelector('.error').textContent=err.message;b.disabled=false}}
function renderTable(){const q=$('#search').value.trim().toLowerCase(),f=$('#status-filter').value,rows=deals.filter(d=>(!f||d.status===f)&&`${d.counterparty} ${d.contract} ${d.company}`.toLowerCase().includes(q));if(!rows.length){$('#table').innerHTML=`<div class="empty"><div class="empty-icon">▤</div><h3>${deals.length?'Сделки не найдены':'Начните с первой сделки'}</h3><p>${deals.length?'Измените запрос или фильтр.':'Создайте досье для проведения проверок.'}</p>${!deals.length&&mayWrite()?'<button class="secondary" id="empty-add">＋ Добавить сделку</button>':''}</div>`;if($('#empty-add'))$('#empty-add').onclick=()=>$('#new-dialog').showModal();return}$('#table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>СДЕЛКА / КОНТРАГЕНТ</th><th>НАПРАВЛЕНИЕ</th><th>СУММА</th><th>ПРОВЕРКИ</th><th>СТАТУС</th></tr></thead><tbody>${rows.map(d=>`<tr><td><button class="link" data-deal="${esc(d.id)}">${esc(d.counterparty)} ↗</button><small>${esc(d.contract)} · ${esc(d.country)}</small></td><td>${d.direction==='import'?'↙ Импорт':'↗ Экспорт'}<small>${esc(d.company)}</small></td><td>${esc(d.amount)} <b>${esc(d.asset)}</b><small>${esc(d.network)}</small></td><td>${d.checks.filter(c=>c.status==='verified').length} / 6</td><td>${badge(d.status)}</td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-deal]').forEach(b=>b.onclick=()=>openDetail(b.dataset.deal))}
function openDetail(id){current=deals.find(d=>d.id===id);if(!current)return;drawDetail();if(!$('#detail-dialog').open)$('#detail-dialog').showModal()}
function drawDetail(){const d=current,screens=d.screenings||[];$('#detail').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">ДОСЬЕ · ${esc(d.contract)}</p><h2>${esc(d.counterparty)}</h2></div><button class="icon" data-close aria-label="Закрыть">×</button></div>${badge(d.status)}<div class="detail-meta">${[['Компания',d.company],['Направление',d.direction==='import'?'Импорт':'Экспорт'],['Страна / регистрация',`${d.country} / ${d.registration}`],['Бенефициар',d.beneficiary||'Не установлен'],['Предмет',d.purpose],['Сумма',`${d.amount} ${d.asset}`],['Сеть',d.network],['Оператор',d.operator||'Не указан'],['Кошелёк',d.wallet||'Не указан'],['Создано',date(d.createdAt)]].map(([t,v])=>`<div><small>${t}</small>${esc(v)}</div>`).join('')}</div><article class="check screening"><h3>Автоматический скрининг адреса</h3><p class="muted">Прямое санкционное совпадение Chainalysis. Чистый результат не исключает косвенные AML-риски.</p>${screens.length?`<div class="screening-list">${screens.map(s=>`<div class="screening-item">${badge(s.status)} · ${esc(s.provider)}<small>${date(s.createdAt)} · совпадений: ${s.matches} · SHA-256 ${esc(s.responseHash)}${s.error?' · '+esc(s.error):''}</small></div>`).join('')}</div>`:'<p class="muted">Запусков ещё нет.</p>'}${mayWrite()?`<button class="secondary" id="run-screening" ${!d.wallet||!auth.amlConfigured?'disabled':''}>Проверить адрес</button>`:''}</article><h3>Проверки и основания</h3>${d.checks.map(c=>`<details class="check"><summary><span>${checks[c.key][0]}</span>${badge(c.status)}</summary><p class="muted">${checks[c.key][1]}</p>${mayWrite()?`<form class="check-form" data-check="${c.key}"><label>Результат<select name="status">${['pending','verified','flagged'].map(s=>`<option value="${s}" ${s===c.status?'selected':''}>${labels[s]}</option>`).join('')}</select></label><label>Основание, источник и дата<textarea required name="evidence" maxlength="3500">${esc(c.evidence)}</textarea></label><p class="muted">${c.updatedAt?'Обновлено: '+date(c.updatedAt)+' · '+esc(c.reviewer):'Не заполнено'}</p><p class="error"></p><button class="secondary">Сохранить результат</button></form>`:`<p class="muted">${esc(c.evidence||'Не заполнено')}${c.reviewer?' · '+esc(c.reviewer):''}</p>`}</details>`).join('')}<h3>Журнал изменений</h3><ol class="history">${[...d.events].reverse().map(e=>`<li><b>${date(e.at)} · ${esc(e.actor)}</b><br>${esc(e.detail)}</li>`).join('')}</ol><p class="muted">Досье не является разрешением на платёж или юридическим заключением.</p><div class="dialog-actions"><button class="secondary" id="print-report">Печать / PDF</button><a class="secondary" href="/api/deals/${encodeURIComponent(d.id)}/report" download>Скачать JSON</a></div>`;$('#print-report').onclick=()=>window.print();if($('#run-screening'))$('#run-screening').onclick=runScreening;document.querySelectorAll('.check-form').forEach(f=>f.onsubmit=saveCheck)}
async function runScreening(){const id=current.id;$('#run-screening').disabled=true;try{await api(`/api/deals/${encodeURIComponent(id)}/screenings`,{method:'POST',body:'{}'});toast('Ответ провайдера сохранён')}catch(e){toast(e.message)}await load();current=deals.find(d=>d.id===id);drawDetail()}
async function saveCheck(e){e.preventDefault();const f=e.target,b=f.querySelector('button'),id=current.id;b.disabled=true;const body=Object.fromEntries(new FormData(f));body.version=current.version;try{const d=await api(`/api/deals/${encodeURIComponent(id)}/checks/${f.dataset.check}`,{method:'PUT',body:JSON.stringify(body)});deals=deals.map(x=>x.id===d.id?d:x);current=d;drawDetail();render();toast('Результат сохранён')}catch(err){f.querySelector('.error').textContent=err.message;b.disabled=false;if(err.status===409)await load()}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)b.closest('dialog').close()});document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
$('#new-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');b.disabled=true;$('#form-error').textContent='';try{const d=await api('/api/deals',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});deals.unshift(d);f.reset();$('#new-dialog').close();render();openDetail(d.id);toast('Досье создано')}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}};
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;$('#login-error').textContent='';try{auth=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});$('#login-dialog').close();identity();await load()}catch(err){$('#login-error').textContent=err.message}finally{b.disabled=false}};
$('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}finally{auth=null;deals=[];$('#login-dialog').showModal()}};
async function load(){try{deals=await api('/api/deals');loadError=''}catch(e){loadError='Не удалось загрузить сделки: '+e.message}render()}
async function init(){try{auth=await api('/api/auth/me');identity();await load()}catch(e){if(e.status===401)$('#login-dialog').showModal();else $('#page').innerHTML=`<div class="error-banner">${esc(e.message)}</div>`}}init();
